name        = "gochar"
license     = "MIT"
description = "Hugo theme by migchar"
homepage    = "https://github.com/migchar/gochar"
customdemo  = "https://migchar.github.io/"
tags        = ["blog", "personal"]
features    = ["social"]
min_version = 1.0

[author]
  name      = "Parker"
  homepage  = "https://migchar.com/"
