# Configure the English version of the site.
#[en]
#  languageCode = "en-us"
#   contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh]
  languageCode = "zh-CN"
  contentDir = "content"
