faviconfile = "img/site/mig-icon-32.png"
logo = "img/site/mig-logo-wide.svg"

avatar = "img/profile/parker-ava-grey.jpg"  # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
author = "Parker"
author_description = ["本硕论文 源码毕设", "如果你需要论文定制或搭建网站，欢迎联系我"]   # author description on left sidebar
proverb = "we have lived, loved, and laughed." # author proverb on bar-top
description = "本硕论文 源码毕设 网站搭建"      # appears in the site header when set to a non-empty string

latestpostscount = 999  # how many posts to display on the home page
bloggroupby = 'year'
dateform = "2006-01-02"
dateformfull = "2006-01-02  Monday  15:04:05"
noshowreadtime = false

# hero
heroDirPathURL = "img/sun.jpg"    # path to image in static dir (for static pages)

# highlighting
highlightjs = false
[prism]
    js="plugins/prism/prism.js"
    css="plugins/prism/prism.css"

# social info
[social_info]
    enable = true
    location = "Zhuhai, China"
    qq = "/img/profile/parker-qq.jpg"
    wechat = "/img/profile/parker-wechat.jpg"
    email = "/img/profile/parker-email.jpg"
    github = "//github.com/migchar"
    twitter = "//twitter.com/zandervin"

# Random word on site reload
[random_word]
    enable = true
    head = "Hello World"
    from_site = "https://sdk.jinrishici.com/v2/browser/jinrishici.js"

[copyright]
    enable = false
    icp = "粤ICP备88888888号"
    from_year = 2016
